- name: yum update all
  yum: name=* state=latest
  become: true

- name: common user alias
  lineinfile:
    dest=/home/opc/.bashrc
    line='alias l=\'ls -lhF\''
    state=present

- name: root alias
  become: true
  lineinfile:
    dest=/root/.bashrc
    line='alias l=\'ls -lhF\''
    state=present

